### ISSUE TITLE
Creating non-starting places consistently fails

### ISSUE THREAD

**Issue by SolarHorizon** [blake-mealey/mantle#110]
When deploying with a configuration that has multiple places in an experience, any places that are not the starting place fail during creation. The resulting error message is HTML for a generic Roblox error page. A new place is actually created on the website during this process, but the steps to upload the place file and apply the configuration are skipped.

I had to pipe the output into a text file because the HTML was too long for my terminal

![image](https://user-images.githubusercontent.com/23710811/149700551-830742e9-aeeb-470f-94a5-bbf15bc0c27d.png)

The program then goes on to skip the file upload & configuration steps for the place that failed, but successfully creates the starting place.

![image](https://user-images.githubusercontent.com/23710811/149700769-7f999722-a33d-44a7-836f-9fb6dd798a78.png)

**Comment by blake-mealey** [comment]
Thanks for the report! I'll take a look tomorrow

**Comment by blake-mealey** [comment]
Btw it looks like there's some issues with the formatting of your output. Are you using a terminal that doesn't support colored output? Would you use a flag to disable colored output (e.g. --no-colors)?

**Comment by SolarHorizon** [comment]
I piped the output into a text file in order to be able to see the full error message because HTML that Roblox spit out is longer than my terminal's scrollback setting, but I can post better screenshots of the errors later if you need them.

**Comment by blake-mealey** [comment]
Oh I understand. No that's fine, thanks

**Comment by blake-mealey** [comment]
I looked into this and unfortunately it seems this is a bug with Roblox's endpoint. You can actually see similar behaviour in Roblox Studio by opening Game Settings, navigating to the "Places" tab, and clicking "Create". You'll see an "Error while adding place" message in the Output view and no place is added to the list. But, if you close Game Settings and reopen it you will see that the place _was_ added.

I will create a report on the devforum and hopefully it will be fixed soon, but for now here's what we can do:

You can go to the experience's configuration page in Roblox and view the list of places. Remove all but one of the created places. For the remaining one, copy its ID and add it to your state file manually. If your state file is remote, you'll have to download it, make the change, then re-upload it manually.

To make the change, open your state file and look for the start place entry (make sure you're looking at the list for the correct environment). It's ID will be `place_start`. Copy that entry and paste it into the list. Modify the following properties:

* `id` - change it to be `place_<name>` where `<name>` is the dictionary key you used in your config file
* `inputs.place.isStart` - `false`
* `outputs.place.assetId` - the asset ID you copied earlier

Run `mantle deploy` again and it should upload the place file and update the place's configuration. Please let me know if this workaround works for you.

I'll also release a new version soon that improves the error message so that your terminal is still usable.

**Comment by blake-mealey** [comment]
Roblox ticket: https://devforum.roblox.com/t/creating-a-place-in-an-experience-with-game-settings-says-it-fails-but-actually-works/1631640

**Comment by SolarHorizon** [comment]
Thank you for getting to this so quickly!

**Comment by blake-mealey** [comment]
I'd also just like to document a potential workaround that I could implement to fix this if Roblox do not fix this issue in the near future:

When creating a new non-starting place, first query the experience for the list of places, then create the new place (expecting a Bad Request response), then query the experience for the updated list of places, and pick the place that was not present initially. This is ofc not ideal as it requires 3 requests instead of 1 but I'll implement it if Roblox doesn't fix their endpoint relatively soon (maybe in a couple months?)

**Comment by blake-mealey** [comment]
This bug seems to have fixed itself now. I can no longer repro it and neither can the Roblox admin who looked at the ticket. Closing this issue.
