### ISSUE TITLE
Getting 413 Payload Too Large

### ISSUE THREAD

**Issue by guidojw** [blake-mealey/mantle#98]
I am getting 413 Payload Too Large errors when running `mantle deploy`.
![image](https://user-images.githubusercontent.com/35309288/146715779-adae647b-b4f2-4170-a457-a33f23de43f6.png)

The place I'm trying to upload is ~650 MB.
If this is me hitting the endpoint's limits, are there any alternatives I can use?

**Comment by blake-mealey** [comment]
Thanks for the report. I'll look into it as soon as possible but I'm guessing it is the endpoint's limit... I'll do some research on potential alternatives.

**Comment by blake-mealey** [comment]
It looks like this is a limitation of the API I am using. I found this forum post with the same issue: https://devforum.roblox.com/t/using-upload-api-with-large-rbxlx-files-consistently-fails/617408

When I get a chance I want to investigate some alternatives, including:

* What endpoint does Studio use to publish places?
* Does the endpoint I currently use support binary files (`.rbxl`) and would that provide sufficient compression to fix your issue?
* Does the Open Cloud API have this issue? If this is the best alternative, can I support the Open Cloud API with an opt-in flag (e.g. `--use-open-cloud`). Note: I switched from Open Cloud because: it can only update place files atm, it cannot update newly created places without the user adding it to the API key's whitelist, and it requires a second type of authentication which complicates the DX

**Comment by guidojw** [comment]
Hi, thanks for the reply!

I looked up Roblox file formats and [this article](https://blog.roblox.com/2013/05/condense-and-compress-our-custom-binary-file-format/) makes it look like (if I understand correctly) your second point may be very true.

I did not realise this issue holds for rojo and remodel too, that's a big blocker for me then 😂

**Comment by blake-mealey** [comment]
Btw for testing purposes, do you know what the primary contributor to file size is for you?

**Comment by guidojw** [comment]
I'm testing it on a train game with 60 trains in a folder in ServerStorage, this folder is 430 MB.
Basically all trains are made of unions and 4 trains have some MeshParts too.

Some examples:
1. Biggest train (23 MB) is an 8 car train made of unions
2. Second biggest train (20 MB) is a 6 car train made of MeshParts
3. Third biggest train (19 MB) is a 6 car train made of unions
4. The smallest train (900 KB) is a simple locomotive with almost no unions

Is that enough information?

**Comment by blake-mealey** [comment]
Alright I did some investigation and it turns out the endpoint I am using is the same as studio's but it looks like they always publish in the `.rbxl` format regardless of the file type you are working in.

I created a test place that is 136MB in rbxlx and 307KB in rbxl and was able to reproduce your error with the rbxlx but was able to deploy the rbxl successfully. I will be releasing a new version that supports rbxl which should be a good workaround for you.

One thing to note is that I believe Rojo considers rbxlx to be a more stable format so you may encounter some issues exporting rbxl files from it (although I don't know what kinds of issues they might be).

**Comment by blake-mealey** [comment]
You can try this in v0.10.3

**Comment by guidojw** [comment]
It's working now, thanks!
